language: objective-c
os: osx
osx_image: xcode8.2

install:
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

env:
 - RAKETASK=test

script:
  - rake "$RAKETASK"
  - Scripts/swiftlint-output.sh
  - Scripts/compile-modules.sh
  - Scripts/compile-output.sh
